from .tipo_especialidad import TipoEspecialidad
from .nota import Nota
from .materia import Materia
from .plan import Plan
from .categoria_cargo import CategoriaCargo
from .tipo_dedicacion import TipoDedicacion
from .especialidad import Especialidad
from .documento import Documento
from .alumno import Alumno
from .grado import Grado
from .grupo import Grupo
from .cargo import Cargo
from .orientacion import Orientacion
from .area import Area
from .departamento import Departamento
from .facultad import Facultad
from .autoridad import Autoridad
from .universidad import Universidad