from .tipoespecialidad_repositorio import TipoEspecialidadRepository
from .nota_repositorio import NotaRepository
from .materia_repositorio import MateriaRepository
from .plan_repositorio import PlanRepository
from .categoriacargo_repositorio import CategoriaCargoRepository
from .tipodedicacion_repositorio import TipoDedicacionRepository
from .especialidad_repositorio import EspecialidadRepository
from .documento_repositorio import DocumentoRepository
from .alumno_repositorio import AlumnoRepository
from .grado_ropositorio import GradoRepository
from .grupo_repositorio import GrupoRepository
from .cargo_repositorio import CargoRepository
from .orientacion_repositorio import OrientacionRepository
from .area_repositorio import AreaRepository
from .departamento_repositorio import DepartamentoRepository
from .facultad_repositorio import FacultadRepository
from .autoridad_repositorio import AutoridadRepository
from .universidad_repositorio import UniversidadRepository
