from .tipoespecialidad_service import TipoEspecialidadService
from .nota_service import NotaService
from .materia_service import MateriaService
from .plan_service import PlanService
from .categoriacargo_service import CategoriaCargoService
from .tipodedicacion_service import TipoDedicacionService
from .especialidad_service import EspecialidadService
from .documento_service import DocumentoService
from .alumno_service import AlumnoService
from .grado_service import GradoService
from .grupo_service import GrupoService
from .cargo_service import CargoService
from .orientacion_service import OrientacionService
from .area_service import AreaService
from .departamento_service import DepartamentoService
from .facultad_service import FacultadService
from .autoridad_service import AutoridadService
from .universidad_service import UniversidadService
